model_path: synthea_ontology/synthea_ontology.ttl
synthea_csv_path: ../synthea/output/1k/csv
output_path: result/1k
chunk_size: 300000
include_dua: True
include_trustscore: True
skip: []
do_shutdown: False
